CREATE TABLE BOARD  (
   BNO BIGINT auto_increment NOT NULL,
   SUBJECT varchar(255) NULL,
   CONTENT varchar(255) NULL,
   WRITER varchar(100) NULL,
   REG_DATE DATE NULL,
   CONSTRAINT BOARD PRIMARY KEY (BNO)
)
